### ISSUE TITLE
Bot wont reply to messages but receives it in console

### ISSUE THREAD

**Issue by migwynkriid** [Hyperclaw79/HyperAI#5]
If i mention the bot with a message incluced, the bot shows the typing... animation but also immediately  gets an error in the console 
![screenshot_54](https://user-images.githubusercontent.com/22034246/47749759-1b857d00-dc8e-11e8-871e-22374361c83c.png)

**Comment by migwynkriid** [comment]
Initiated Brain ClientSession.
HyperAI is now live!
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 32, in on_ready
    await self.change_presence(game=game)
TypeError: change_presence() got an unexpected keyword argument 'game'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 371, in on_message
    await self.chatbot(message)
  File "bot.py", line 349, in chatbot
    response, status = await self.brain.query(message.content)
TypeError: 'NoneType' object is not iterable

**Comment by Hyperclaw79** [comment]
Fixed in https://github.com/Hyperclaw79/HyperAI/commit/3fe10fbef60e8aaa192cae4efd50fabc141b96e5.
